In [1]:
import pandas as pd
import numpy as np
import os

#import from csv and create win cols
pd.set_option('display.max_rows', 200)
X = pd.read_csv('nfl_team_stats_2002-2024.csv')
X['home'] = X['home'].astype(str)
X['away'] = X['away'].astype(str)
X['home_win'] = X['score_home'] > X['score_away']
X['home_win'] = X['home_win'].astype(int)

X['points_allowed_home'] = X['score_away']
X['points_allowed_away'] = X['score_home']
X['yards_allowed_home'] = X['yards_away']
X['yards_allowed_away'] = X['yards_home']
#if you tie at home means the other team "won" as they dont have home field advantage
X

,season,week,date,time_et,neutral,away,home,score_away,score_home,first_downs_away,...,interceptions_home,def_st_td_away,def_st_td_home,possession_away,possession_home,home_win,points_allowed_home,points_allowed_away,yards_allowed_home,yards_allowed_away
0,2002,1,2002-09-05,8:30 PM,False,49ers,Giants,16,13,13,...,3,0,0,27:32,32:28,0,16,13,279,361
1,2002,1,2002-09-08,1:00 PM,False,Colts,Jaguars,28,25,18,...,1,2,0,27:27,32:33,0,28,25,307,343
2,2002,1,2002-09-08,1:00 PM,False,Cardinals,Commanders,23,31,14,...,1,0,0,25:36,34:24,1,23,31,257,442
3,2002,1,2002-09-08,1:00 PM,False,Lions,Dolphins,21,49,15,...,0,0,2,25:36,34:24,1,21,49,257,389
4,2002,1,2002-09-08,1:00 PM,False,Eagles,Titans,24,27,17,...,1,0,0,29:12,30:48,1,24,27,261,328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6209,2024,Division,2025-01-19,3:00 PM,False,Rams,Eagles,22,28,18,...,0,0,0,29:06,30:54,1,22,28,402,350
6210,2024,Division,2025-01-19,6:30 PM,False,Ravens,Bills,25,27,23,...,0,0,0,28:16,31:44,1,25,27,416,273
6211,2024,Conference,2025-01-26,3:00 PM,False,Commanders,Eagles,23,55,22,...,0,0,0,29:29,30:31,1,23,55,350,459
6212,2024,Conference,2025-01-26,6:30 PM,False,Bills,Chiefs,29,32,22,...,0,0,0,30:32,29:28,1,29,32,374,368
6213,2024,Superbowl,2025-02-09,6:30 PM,True,Chiefs,Eagles,22,40,12,...,1,0,1,23:02,36:58,1,22,40,275,345

In [3]:
def poss_to_seconds(val):
    try:
        m, s = map(int, val.split(':'))
        return m * 60 + s
    except:
        return np.nan
    
#change pos to singular number 
X.loc[:, 'possession_home'] = X['possession_home'].apply(poss_to_seconds)
X.loc[:, 'possession_away'] = X['possession_away'].apply(poss_to_seconds)
X.loc[:,'week'] = pd.to_numeric(X['week'], errors='coerce')
X = X.dropna(subset=['week'])
X= X.copy()


X.loc[:,'game_id'] = X.index

In [4]:
#Find Home Cols and Away cols and split up dataframe based on them to simplify cols and be able to track each team whether they are home or away
home_cols = [col for col in X.columns if col.endswith('_home')]
away_cols = [col for col in X.columns if col.endswith('_away')]

home_df = X[['season', 'week', 'game_id', 'home', 'home_win'] + home_cols].copy()
away_df = X[['season', 'week', 'game_id', 'away'] + away_cols].copy()

home_df = home_df.rename(columns=lambda x: x.replace('_home', '') if x.endswith('_home') else x)
away_df = away_df.rename(columns=lambda x: x.replace('_away', '') if x.endswith('_away') else x)

home_df = home_df.rename(columns={'home': 'team'})
away_df = away_df.rename(columns={'away': 'team'})

In [5]:
long_X = pd.concat([home_df, away_df], ignore_index=True)
long_X = long_X.sort_values(by =['season', 'team', 'week'])
#print(long_X.head(200))

stat_cols = [col for col in long_X.columns if col not in ['season', 'week', 'team', 'game_id', 'home_win']]
print(stat_cols)

#rolling average, shifted by one so all we know are the stats leading up to that game for the current season averages.
rolling_avg = (
    long_X
    .groupby(['season', 'team'])[stat_cols]
    .transform(lambda x: x.shift(1).expanding().mean())
)
print(rolling_avg)

long_X = long_X.sort_values(by=['season', 'team', 'week'])
rolling_X = pd.concat([long_X[['season', 'week', 'team', 'game_id', 'home_win']], rolling_avg], axis=1)
print(rolling_X.head(30))

#merge the two df back together and label to be able to tell which team was the home team
home_stats = rolling_X.merge(X[['game_id', 'home']], left_on=['game_id', 'team'], right_on=['game_id', 'home'])
away_stats = rolling_X.merge(X[['game_id', 'away']], left_on=['game_id', 'team'], right_on=['game_id', 'away'])

home_stats = home_stats.add_suffix('_home')
away_stats = away_stats.add_suffix('_away')

#final merge of home and away stats
final_X = pd.merge(home_stats, away_stats, left_on='game_id_home', right_on='game_id_away')
final_X = final_X.rename(columns={'game_id_home': 'game_id'}).drop(columns=['game_id_away'])

#drop cols that are week 1 as we do not have any existing information about their season yet.
final_X = final_X[final_X['week_home'] > 1].copy()

['score', 'first_downs', 'first_downs_from_passing', 'first_downs_from_rushing', 'first_downs_from_penalty', 'third_down_comp', 'third_down_att', 'fourth_down_comp', 'fourth_down_att', 'plays', 'drives', 'yards', 'pass_comp', 'pass_att', 'pass_yards', 'sacks_num', 'sacks_yards', 'rush_att', 'rush_yards', 'pen_num', 'pen_yards', 'redzone_comp', 'redzone_att', 'fumbles', 'interceptions', 'def_st_td', 'possession', 'points_allowed', 'yards_allowed']
           score  first_downs  first_downs_from_passing  \
5951         NaN          NaN                       NaN
29     16.000000    13.000000                  7.000000
41     15.000000    15.500000                  9.000000
70     16.666667    17.666667                  8.333333
6038   21.750000    18.500000                  8.750000
...          ...          ...                       ...
5876   24.750000    20.583333                 11.833333
5901   26.076923    20.769231                 12.076923
11864  26.357143    21.000000                 12.214286
5932   26.400000    20.866667                 12.200000
11901  26.437500    21.187500                 12.687500

       first_downs_from_rushing  first_downs_from_penalty  third_down_comp  \
5951                        NaN                       NaN              NaN
29                     5.000000                  1.000000         4.000000
41                     6.000000                  0.500000         6.000000
70                     9.000000                  0.333333         6.000000
6038                   9.250000                  0.500000         5.500000
...                         ...                       ...              ...
5876                   6.250000                  2.500000         4.416667
5901                   6.153846                  2.538462         4.692308
11864                  6.285714                  2.500000         4.857143
5932                   6.200000                  2.466667         4.733333
11901                  6.062500                  2.437500         4.812500

       third_down_att  fourth_down_comp  fourth_down_att      plays  ...  \
5951              NaN               NaN              NaN        NaN  ...
29          12.000000          0.000000         0.000000  51.000000  ...
41          12.500000          0.000000         0.000000  54.500000  ...
70          13.000000          0.000000         0.000000  60.000000  ...
6038        12.000000          0.000000         0.000000  58.750000  ...
...               ...               ...              ...        ...  ...
5876        11.416667          0.416667         0.666667  61.083333  ...
5901        11.461538          0.384615         0.615385  60.692308  ...
11864       11.642857          0.357143         0.642857  61.428571  ...
5932        11.666667          0.400000         0.666667  61.466667  ...
11901       11.687500          0.375000         0.625000  62.000000  ...

        pen_num  pen_yards  redzone_comp  redzone_att   fumbles  \
5951        NaN        NaN           NaN          NaN       NaN
29     5.000000  29.000000      0.000000     8.000000  0.000000
41     7.500000  71.500000      0.000000     6.500000  0.500000
70     6.666667  64.333333      0.000000     6.000000  0.333333
6038   6.000000  55.000000      0.000000     6.250000  0.250000
...         ...        ...           ...          ...       ...
5876   6.166667  50.583333      1.916667     3.583333  0.750000
5901   6.153846  49.384615      2.076923     3.615385  0.692308
11864  6.428571  49.857143      2.142857     3.642857  0.642857
5932   6.466667  51.200000      2.133333     3.533333  0.600000
11901  6.500000  50.937500      2.125000     3.562500  0.562500

       interceptions  def_st_td  possession  points_allowed  yards_allowed
5951             NaN        NaN         NaN             NaN            NaN
29          1.000000   0.000000         NaN       13.000000     361.000000
41          1.000000   0.000000         NaN       18.500000     330.000000
70          1.000000   0.000000         NaN       15.666667     292.333333
6038        0.750000   0.500000         NaN       15.000000     297.500000
...              ...        ...         ...             ...            ...
5876        0.833333   0.250000         NaN       18.250000     324.666667
5901        0.769231   0.230769         NaN       18.461538     337.846154
11864       0.785714   0.214286         NaN       18.000000     334.000000
5932        0.733333   0.200000         NaN       18.400000     335.800000
11901       0.750000   0.187500         NaN       18.812500     331.750000

[11902 rows x 29 columns]
      season  week   team  game_id  home_win      score  first_downs  \
5951    2002   1.0  49ers        0       NaN        NaN          NaN
29      2002   2.0  49ers       29       0.0  16.000000    13.000000
41      2002   3.0  49ers       41       1.0  15.000000    15.500000
70      2002   5.0  49ers       70       1.0  16.666667    17.666667
6038    2002   6.0  49ers       87       NaN  21.750000    18.500000
6042    2002   7.0  49ers       91       NaN  23.000000    19.600000
111     2002   8.0  49ers      111       1.0  23.666667    20.666667
6078    2002   9.0  49ers      127       NaN  25.714286    20.285714
141     2002  10.0  49ers      141       1.0  25.375000    21.500000
6104    2002  11.0  49ers      153       NaN  24.444444    21.555556
175     2002  12.0  49ers      175       0.0  23.700000    21.500000
189     2002  13.0  49ers      189       1.0  23.090909    21.727273
6150    2002  14.0  49ers      199       NaN  23.750000    21.666667
221     2002  15.0  49ers      221       0.0  24.307692    22.000000
6176    2002  16.0  49ers      225       NaN  23.571429    21.571429
6206    2002  17.0  49ers      255       NaN  23.133333    21.533333
8       2002   1.0  Bears        8       1.0        NaN          NaN
5974    2002   2.0  Bears       23       NaN  27.000000    20.000000
35      2002   3.0  Bears       35       0.0  20.500000    16.500000
5997    2002   4.0  Bears       46       NaN  21.333333    18.000000
73      2002   5.0  Bears       73       0.0  22.750000    17.250000
6045    2002   7.0  Bears       94       NaN  22.400000    17.800000
6061    2002   8.0  Bears      110       NaN  22.000000    17.666667
118     2002   9.0  Bears      118       0.0  19.857143    16.857143
140     2002  10.0  Bears      140       0.0  19.000000    17.000000
6110    2002  11.0  Bears      159       NaN  20.222222    16.666667
168     2002  12.0  Bears      168       1.0  19.800000    16.600000
6136    2002  13.0  Bears      185       NaN  19.818182    17.000000
6158    2002  14.0  Bears      207       NaN  19.833333    17.166667
216     2002  15.0  Bears      216       1.0  19.000000    16.769231

      first_downs_from_passing  first_downs_from_rushing  \
5951                       NaN                       NaN
29                    7.000000                  5.000000
41                    9.000000                  6.000000
70                    8.333333                  9.000000
6038                  8.750000                  9.250000
6042                  9.000000                  9.400000
111                  10.666667                  9.000000
6078                 10.571429                  8.571429
141                  10.875000                  9.250000
6104                 10.777778                  9.555556
175                  11.200000                  9.000000
189                  11.727273                  8.727273
6150                 11.750000                  8.666667
221                  11.923077                  8.846154
6176                 11.500000                  8.857143
6206                 11.600000                  8.733333
8                          NaN                       NaN
5974                 12.000000                  6.000000
35                   10.000000                  5.500000
5997                 11.666667                  5.000000
73                   11.000000                  4.500000
6045                 12.200000                  4.000000
6061                 11.666667                  4.333333
118                  11.000000                  4.000000
140                  10.625000                  4.375000
6110                 10.111111                  4.777778
168                   9.700000                  5.000000
6136                 10.545455                  4.727273
6158                 10.750000                  4.666667
216                  10.307692                  4.769231

      first_downs_from_penalty  ...   pen_num  pen_yards  redzone_comp  \
5951                       NaN  ...       NaN        NaN           NaN
29                    1.000000  ...  5.000000  29.000000           0.0
41                    0.500000  ...  7.500000  71.500000           0.0
70                    0.333333  ...  6.666667  64.333333           0.0
6038                  0.500000  ...  6.000000  55.000000           0.0
6042                  1.200000  ...  6.400000  54.200000           0.0
111                   1.000000  ...  6.166667  52.166667           0.0
6078                  1.142857  ...  5.714286  48.285714           0.0
141                   1.375000  ...  5.375000  47.250000           0.0
6104                  1.222222  ...  5.111111  43.666667           0.0
175                   1.300000  ...  5.400000  46.400000           0.0
189                   1.272727  ...  5.727273  50.000000           0.0
6150                  1.250000  ...  5.416667  46.666667           0.0
221                   1.230769  ...  5.692308  48.384615           0.0
6176                  1.214286  ...  5.500000  46.214286           0.0
6206                  1.200000  ...  5.400000  45.133333           0.0
8                          NaN  ...       NaN        NaN           NaN
5974                  2.000000  ...  4.000000  33.000000           0.0
35                    1.000000  ...  5.500000  56.000000           0.0
5997                  1.333333  ...  6.000000  53.666667           0.0
73                    1.750000  ...  5.750000  54.000000           0.0
6045                  1.600000  ...  6.000000  56.200000           0.0
6061                  1.666667  ...  5.833333  53.500000           0.0
118                   1.857143  ...  5.857143  50.571429           0.0
140                   2.000000  ...  6.625000  59.375000           0.0
6110                  1.777778  ...  6.444444  56.111111           0.0
168                   1.900000  ...  6.300000  55.500000           0.0
6136                  1.727273  ...  6.272727  56.272727           0.0
6158                  1.750000  ...  6.166667  54.833333           0.0
216                   1.692308  ...  6.076923  54.846154           0.0

      redzone_att   fumbles  interceptions  def_st_td  possession  \
5951          NaN       NaN            NaN        NaN         NaN
29       8.000000  0.000000       1.000000   0.000000         NaN
41       6.500000  0.500000       1.000000   0.000000         NaN
70       6.000000  0.333333       1.000000   0.000000         NaN
6038     6.250000  0.250000       0.750000   0.500000         NaN
6042     6.400000  0.200000       0.600000   0.400000         NaN
111      6.833333  0.333333       0.666667   0.333333         NaN
6078     6.714286  0.285714       0.571429   0.285714         NaN
141      6.875000  0.375000       0.500000   0.250000         NaN
6104     6.777778  0.333333       0.555556   0.222222         NaN
175      6.300000  0.300000       0.600000   0.200000         NaN
189      6.636364  0.272727       0.545455   0.181818         NaN
6150     6.500000  0.250000       0.666667   0.250000         NaN
221      6.538462  0.307692       0.615385   0.230769         NaN
6176     6.428571  0.285714       0.642857   0.214286         NaN
6206     6.333333  0.333333       0.666667   0.200000         NaN
8             NaN       NaN            NaN        NaN         NaN
5974     6.000000  1.000000       1.000000   0.000000         NaN
35       5.500000  1.000000       1.000000   0.000000         NaN
5997     6.333333  1.000000       1.000000   0.000000         NaN
73       6.750000  0.750000       0.750000   0.500000         NaN
6045     7.200000  0.800000       1.200000   0.400000         NaN
6061     6.833333  1.000000       1.166667   0.333333         NaN
118      6.571429  1.000000       1.285714   0.285714         NaN
140      6.625000  1.000000       1.125000   0.250000         NaN
6110     6.777778  0.888889       1.111111   0.222222         NaN
168      6.500000  0.800000       1.000000   0.200000         NaN
6136     6.363636  0.818182       0.909091   0.181818         NaN
6158     6.583333  1.000000       0.916667   0.166667         NaN
216      6.615385  1.000000       1.076923   0.153846         NaN

      points_allowed  yards_allowed
5951             NaN            NaN
29         13.000000     361.000000
41         18.500000     330.000000
70         15.666667     292.333333
6038       15.000000     297.500000
6042       16.200000     304.800000
111        19.333333     324.333333
6078       20.571429     338.000000
141        20.500000     325.625000
6104       19.666667     317.888889
175        19.700000     330.200000
189        21.363636     331.363636
6150       21.583333     346.000000
221        22.000000     339.153846
6176       21.857143     336.500000
6206       21.333333     326.333333
8                NaN            NaN
5974       23.000000     368.000000
35         18.000000     312.500000
5997       21.666667     309.000000
73         24.500000     334.250000
6045       26.400000     358.800000
6061       25.833333     359.333333
118        25.714286     360.000000
140        24.875000     353.625000
6110       25.777778     358.444444
168        25.300000     361.400000
6136       24.545455     355.909091
6158       25.000000     359.250000
216        25.153846     365.153846

[30 rows x 34 columns]

In [6]:
#tweak the names for more readability and drop repeat cols that we do not need.
final_X['week'] = final_X['week_home']
final_X['week'] = final_X['week_home']
final_X['season'] = final_X['season_home']
final_X['home_win'] = final_X['home_win_home']
final_X = final_X.drop(['season_home', 'week_home', 'home_home', 'season_away', 'week_away', 'away_away', 'home_win_home', 'home_win_away'], axis =1)

print(final_X.columns)
final_X.head(30)

Index(['team_home', 'game_id', 'score_home', 'first_downs_home',
       'first_downs_from_passing_home', 'first_downs_from_rushing_home',
       'first_downs_from_penalty_home', 'third_down_comp_home',
       'third_down_att_home', 'fourth_down_comp_home', 'fourth_down_att_home',
       'plays_home', 'drives_home', 'yards_home', 'pass_comp_home',
       'pass_att_home', 'pass_yards_home', 'sacks_num_home',
       'sacks_yards_home', 'rush_att_home', 'rush_yards_home', 'pen_num_home',
       'pen_yards_home', 'redzone_comp_home', 'redzone_att_home',
       'fumbles_home', 'interceptions_home', 'def_st_td_home',
       'possession_home', 'points_allowed_home', 'yards_allowed_home',
       'team_away', 'score_away', 'first_downs_away',
       'first_downs_from_passing_away', 'first_downs_from_rushing_away',
       'first_downs_from_penalty_away', 'third_down_comp_away',
       'third_down_att_away', 'fourth_down_comp_away', 'fourth_down_att_away',
       'plays_away', 'drives_away', 'yards_away', 'pass_comp_away',
       'pass_att_away', 'pass_yards_away', 'sacks_num_away',
       'sacks_yards_away', 'rush_att_away', 'rush_yards_away', 'pen_num_away',
       'pen_yards_away', 'redzone_comp_away', 'redzone_att_away',
       'fumbles_away', 'interceptions_away', 'def_st_td_away',
       'possession_away', 'points_allowed_away', 'yards_allowed_away', 'week',
       'season', 'home_win'],
      dtype='object')

,team_home,game_id,score_home,first_downs_home,first_downs_from_passing_home,first_downs_from_rushing_home,first_downs_from_penalty_home,third_down_comp_home,third_down_att_home,fourth_down_comp_home,...,redzone_att_away,fumbles_away,interceptions_away,def_st_td_away,possession_away,points_allowed_away,yards_allowed_away,week,season,home_win
0,49ers,29,16.000000,13.000000,7.000000,5.000000,1.000000,4.000000,12.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,NaN,16.000000,327.000000,2.0,2002,0.0
1,49ers,41,15.000000,15.500000,9.000000,6.000000,0.500000,6.000000,12.500000,0.000000,...,5.500000,0.500000,1.500000,0.500000,NaN,30.000000,354.000000,3.0,2002,1.0
2,49ers,70,16.666667,17.666667,8.333333,9.000000,0.333333,6.000000,13.000000,0.000000,...,4.250000,1.000000,2.250000,0.000000,NaN,22.000000,313.000000,5.0,2002,1.0
3,49ers,111,23.666667,20.666667,10.666667,9.000000,1.000000,6.333333,12.000000,0.000000,...,3.666667,0.500000,0.833333,0.500000,NaN,15.500000,334.333333,8.0,2002,1.0
4,49ers,141,25.375000,21.500000,10.875000,9.250000,1.375000,7.125000,13.000000,0.250000,...,7.875000,0.125000,1.250000,0.000000,NaN,30.000000,438.000000,10.0,2002,1.0
5,49ers,175,23.700000,21.500000,11.200000,9.000000,1.300000,7.600000,14.000000,0.400000,...,6.000000,0.900000,0.600000,0.000000,NaN,16.700000,282.900000,12.0,2002,0.0
6,49ers,189,23.090909,21.727273,11.727273,8.727273,1.272727,7.727273,14.545455,0.454545,...,6.090909,0.545455,0.818182,0.454545,NaN,22.636364,379.909091,13.0,2002,1.0
7,49ers,221,24.307692,22.000000,11.923077,8.846154,1.230769,8.000000,15.076923,0.538462,...,6.461538,0.923077,1.000000,0.615385,NaN,20.923077,323.076923,15.0,2002,0.0
9,Bears,35,20.500000,16.500000,10.000000,5.500000,1.000000,5.500000,13.000000,0.000000,...,4.000000,0.000000,1.500000,2.000000,NaN,20.000000,345.000000,3.0,2002,0.0
10,Bears,73,22.750000,17.250000,11.000000,4.500000,1.750000,5.750000,13.750000,0.250000,...,5.500000,1.500000,0.750000,0.500000,NaN,28.500000,333.500000,5.0,2002,0.0
11,Bears,118,19.857143,16.857143,11.000000,4.000000,1.857143,5.428571,13.142857,0.285714,...,5.142857,0.857143,0.571429,0.000000,NaN,15.000000,267.857143,9.0,2002,0.0
12,Bears,140,19.000000,17.000000,10.625000,4.375000,2.000000,4.875000,12.875000,0.375000,...,5.750000,0.625000,1.125000,0.500000,NaN,20.625000,309.500000,10.0,2002,0.0
13,Bears,168,19.800000,16.600000,9.700000,5.000000,1.900000,4.700000,13.300000,0.500000,...,5.700000,0.400000,1.400000,0.500000,NaN,29.100000,367.400000,12.0,2002,1.0
14,Bears,216,19.000000,16.769231,10.307692,4.769231,1.692308,4.384615,13.307692,0.692308,...,5.692308,0.615385,0.769231,0.307692,NaN,21.692308,358.384615,15.0,2002,1.0
15,Bears,254,18.733333,16.400000,10.000000,4.866667,1.533333,4.466667,13.266667,0.600000,...,4.600000,0.733333,0.666667,0.733333,NaN,13.066667,255.066667,17.0,2002,0.0
17,Bengals,54,5.333333,17.333333,10.000000,5.333333,2.000000,6.000000,14.666667,0.000000,...,4.000000,0.333333,0.333333,1.666667,NaN,13.333333,299.666667,4.0,2002,0.0
18,Bengals,81,8.800000,17.200000,10.200000,5.200000,1.800000,4.400000,14.400000,0.800000,...,7.000000,1.750000,1.750000,0.000000,NaN,26.250000,341.750000,6.0,2002,0.0
19,Bengals,109,8.500000,17.333333,10.333333,5.333333,1.666667,5.000000,14.333333,0.666667,...,5.500000,0.833333,1.500000,0.333333,NaN,28.833333,344.166667,8.0,2002,0.0
20,Bengals,151,15.555556,19.000000,11.222222,6.555556,1.222222,5.333333,13.666667,0.444444,...,5.333333,0.666667,1.111111,0.333333,NaN,21.666667,349.666667,11.0,2002,0.0
21,Bengals,183,16.454545,18.363636,11.181818,6.181818,1.000000,5.454545,13.636364,0.454545,...,5.454545,1.181818,0.818182,0.363636,NaN,20.636364,339.000000,13.0,2002,0.0
22,Bengals,215,18.076923,19.384615,11.846154,6.230769,1.307692,5.538462,13.923077,0.692308,...,5.384615,0.384615,0.615385,0.076923,NaN,19.384615,343.461538,15.0,2002,0.0
23,Bengals,232,17.857143,19.357143,11.857143,6.142857,1.357143,5.642857,14.142857,0.714286,...,7.000000,0.857143,0.928571,0.642857,NaN,25.571429,364.285714,16.0,2002,1.0
25,Bills,46,33.000000,23.000000,16.666667,4.000000,2.333333,5.666667,14.333333,0.666667,...,6.333333,1.000000,1.000000,0.000000,NaN,21.666667,309.000000,4.0,2002,1.0
26,Bills,62,33.000000,23.750000,17.250000,4.250000,2.250000,5.500000,13.500000,0.500000,...,5.000000,0.666667,1.000000,1.666667,NaN,19.666667,296.333333,5.0,2002,0.0
27,Bills,106,31.000000,23.428571,15.285714,5.285714,2.857143,5.428571,13.714286,0.428571,...,5.833333,0.666667,1.333333,0.833333,NaN,31.500000,366.500000,8.0,2002,1.0
28,Bills,117,30.125000,23.375000,15.125000,5.125000,3.125000,5.500000,13.750000,0.500000,...,5.714286,0.714286,1.285714,0.571429,NaN,22.571429,306.428571,9.0,2002,0.0
29,Bills,184,25.181818,23.000000,14.727273,5.363636,2.909091,5.363636,13.090909,0.545455,...,5.909091,0.818182,1.090909,0.363636,NaN,17.272727,282.909091,13.0,2002,1.0
30,Bills,217,25.538462,22.923077,14.384615,5.692308,2.846154,5.923077,13.307692,0.461538,...,6.230769,0.538462,1.153846,0.615385,NaN,22.461538,370.076923,15.0,2002,1.0
31,Bills,246,23.466667,22.133333,13.533333,5.666667,2.933333,5.466667,13.133333,0.400000,...,6.466667,0.800000,1.333333,0.466667,NaN,28.600000,329.400000,17.0,2002,1.0
33,Broncos,39,23.500000,19.500000,10.000000,7.500000,2.000000,3.500000,10.000000,0.500000,...,9.000000,0.500000,1.000000,1.500000,NaN,38.000000,357.500000,3.0,2002,1.0

In [ ]:
#lets convert this into a csv file so myself and others can use in in ML models
final_X.to_csv('final_nfl_rolling_stats.csv', index=False)